---
- hosts: localhost
  vars:
    subscription_id=2489a3c7-9e54-4074-a38d-eb3af3bdc14f
    client_id=598fe56e-920e-428d-b16a-4b9386497ce3
    secret=VU05y3-dw-hH1ZdUOztp~k5g.p.B7WPgUT
    tenant=c0447ee7-7b4a-40e6-85b3-dc6eda2714de
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: Testing
        location: eastus
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: Testing
        name: testvn001
        address_prefixes: "15.0.0.0/16"
    - name: Add subnet
      azure_rm_subnet:
        resource_group: Testing
        name: subnet001
        address_prefix: "15.0.0.0/24"
        virtual_network: testvn001

